### ISSUE TITLE
dependency on xchange 4.2.0

### ISSUE THREAD

**Issue by npomfret** [bitrich-info/xchange-stream#11]
I'm trying out this project (4.2.3-SNAPSHOT) and have a dependency on the xchange project snapshot 4.2.1.  This project however appears to required an older version of xchange (4.2.0) and so I'm getting a bunch of NoSuchMethodErrors.  Has this problem been solved?

**Comment by dozd** [comment]
I'm afraid no. Because release 4.2.1 of xchange had a few API breaking changes and was the first version xchange-stream supports.

**Comment by npomfret** [comment]
Ok, do you know if there a plan to migrate the stream project to the latest xchange?

**Comment by dozd** [comment]
Blah i was mistaken. Yeah i can have a look at it.

**Comment by dozd** [comment]
Can you provide details? I'm a little lost. It should work with xchange 4.2.0 fine.

**Comment by dozd** [comment]
Snapshot version of xchange-stream must be adopted to latest snapshot xchange version.

**Comment by dozd** [comment]
Check branch xchange-4.2.1-SNAPSHOT. I don't want snapshot dependency in develop to have stable build.

**Comment by dozd** [comment]
Updated to latest Xchange version in develop, will be release shortly into central.
